AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Sam Template

Globals:
  Function:
    Timeout: 180

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "FastAPILambda"
      MemorySize: 256
      CodeUri: src
      Handler: app.main.handler
      Runtime: python3.9
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi
    StageName: prod

Outputs:
  ApiUrl:
    Description: API endpoint URL
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'